### ISSUE TITLE
Investigate SuomiSport integration

### ISSUE THREAD

**Issue by Clpsplug** [Clpsplug/ERP#25]
Related: #21. Figure out where to get a CSV.

**Comment by Clpsplug** [comment]
I need backup; Most of the content is in Finnish and I'm having trouble reading them

**Comment by jpaivarinta** [comment]
Suomisport: first log in (credentials in Drive)

OULUN MIEKKAILUSEURA-events:
https://www.suomisport.fi/administration/sportsfederations/2741/club/2757/events#
download excel-file: 
https://www.suomisport.fi/api/v1/event/export/listing/club/2757


Oulun miekkailuseura ry -events:
https://www.suomisport.fi/administration/sportsfederations/5376/club/9489#
download excel-file:
https://www.suomisport.fi/api/v1/event/export/listing/club/9489
