### ISSUE TITLE
XLSX to CSV converter

### ISSUE THREAD

**Issue by Kivike** [Clpsplug/ERP#27]
See design in https://drive.google.com/file/d/1dwZniK8GnDkLJvukenj7z6wnwsESMesm/view?usp=sharing

-Implement class that converts .xlsx formatted file to .csv file

**Comment by Clpsplug** [comment]
From #26:  
SuomiSport dumps payment data into XLSX. We need a way to read it.  
https://github.com/box/spout looks good for the purpose
